export const LOGIN = 'LOGIN';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';




export const GET_GLOBAL_DATA = 'GET_GLOBAL_DATA';
export const SET_GLOBAL_DATA = 'SET_GLOBAL_DATA';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const GET_PERSON_LIST_DATA = 'GET_PERSON_LIST_DATA';
export const SET_PERSON_LIST_DATA = 'SET_PERSON_LIST_DATA';
export const GET_PERSON_DATA = 'GET_PERSON_DATA';
export const SET_PERSON_DATA = 'SET_PERSON_DATA';
export const GET_FRIEND_DATA = 'GET_FRIEND_DATA';
export const SET_FRIEND_DATA = 'SET_FRIEND_DATA';
export const GET_FRIENDS_LIST_DATA = 'GET_FRIENDS_LIST';
export const SET_FRIENDS_LIST_DATA = 'SET_FRIENDS_LIST';
export const GET_PERSONS_BY_NAME_DATA = 'GET_PERSONS_BY_NAME_DATA';
export const SET_PERSONS_BY_NAME_DATA = 'SET_PERSONS_BY_NAME_DATA';
export const GET_FILTER_DATA = 'GET_FILTER_DATA';
export const SET_FILTER_DATA = 'SET_FILTER_DATA';
export const SET_FILTER_DATA_FROM_FILTER = 'SET_FILTER_DATA_FROM_FILTER';
export const GET_LIST_DATA_FROM_FILTER = 'GET_LIST_DATA_FROM_FILTER';
export const SET_LIST_DATA_FROM_FILTER = 'SET_LIST_DATA_FROM_FILTER';
export const REMOVE_CLEAR_FILTERS_BUTTON = 'REMOVE_CLEAR_FILTERS_BUTTON';